import { existsSync } from "node:fs";
import { mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, relative } from "node:path";
import type { AgentGraph } from "../agents/catalog.js";
import type { AgentSpec } from "../domain/types.js";
import { fromRepoRoot, fromSdkRoot } from "../config/paths.js";
import { loadAgentProfile, type AgentProfile } from "./agent-profiles.js";
import { readFrontmatter } from "./markdown.js";
import { discoverSkills, SKILLS_ROOT, ungrantedSkills } from "./skills.js";
import { scriptToolName, type ToolCatalog } from "../../assets/tools/catalog.js";
import { commandLine } from "../../assets/tools/script/registry.js";

/**
 * `.claude/` holds generated POINTERS only; the content has exactly one home under
 * `src/agent-sdk/assets`. Three kinds, all regenerated by `pnpm agents:shims` and
 * verified by `pnpm agents:check`:
 *
 *  - `.claude/skills/<skill>/SKILL.md`  the operator's slash-command for each skill
 *  - `.claude/skills/<agent>/SKILL.md`  `/<agent>` for EVERY agent, named exactly after it: a pointer
 *    carrying `agent_profile:` and the run contract (an orchestrator's also names its roster)
 *  - `.claude/agents/<subagent>.md`     a native Claude Code subagent with the profile inlined;
 *    one per graph subagent and never one per orchestrator
 */
export const GENERATED_NOTE = "<!-- Generated by `pnpm agents:shims` from src/agent-sdk/assets. Do not edit; edit the source and regenerate. -->";

export const RUN_CONTRACT = "src/agent-sdk/assets/docs/USERGUIDE.md#run-a-profile-in-session";
const NATIVE_TOOLS = new Set(["Read", "Glob", "Grep", "Bash", "Write", "Edit", "WebSearch", "WebFetch"]);
const repoRel = (path: string) => relative(fromRepoRoot(), path);
const yamlString = (value: string) => JSON.stringify(value);

function frontmatter(fields: Record<string, string | undefined>): string {
  return `---\n${Object.entries(fields).filter(([, v]) => v !== undefined).map(([k, v]) => `${k}: ${v}`).join("\n")}\n---\n`;
}

const bullets = (items: string[]) => items.map((item) => `- ${item}`).join("\n");
const numbered = (items: string[]) => items.map((item, i) => `${i + 1}. ${item}`).join("\n");

function skillLines(profile: AgentProfile, skills: Map<string, string>): string[] {
  return profile.skills.map(({ name, disclosure }) => {
    const path = skills.get(name);
    if (!path) throw new Error(`Profile grants missing skill '${name}'`);
    return `\`${repoRel(path)}\` (${disclosure === "mandatory" ? "read it first and follow it" : "read it when you start that work"})`;
  });
}

async function guideLines(profile: AgentProfile, toolCatalog: ToolCatalog): Promise<string[]> {
  const rows: string[] = [];
  for (const { name } of profile.tools) {
    const entry = toolCatalog.groups.get(name);
    if (!entry) throw new Error(`Profile grants unknown tool family '${name}'`);
    rows.push(`\`${name}\`: ${entry.summary} Guardrails: \`${repoRel(entry.guidePath)}\``);
  }
  return rows;
}

/** The script tools a profile's families grant, as the commands a session runs through Bash (a session has no `mcp__invest__*` tools). */
function scriptLines(profile: AgentProfile, toolCatalog: ToolCatalog): string[] {
  const families = new Set(profile.tools.map((grant) => grant.name));
  return toolCatalog.scripts.filter((spec) => families.has(spec.family)).map((spec) => `\`${spec.name}\`${spec.metered ? " (METERED: ask the operator first)" : ""}: \`${commandLine(spec)}\``);
}

async function skillShim(name: string, path: string): Promise<string> {
  const { attributes } = await readFrontmatter(path);
  const scripts = existsSync(fromSdkRoot("assets/tools/repo", name)) ? `; its scripts are under \`src/agent-sdk/assets/tools/repo/${name}/\`` : "";
  return `${frontmatter({ name, description: attributes.description, "argument-hint": attributes["argument-hint"] })}${GENERATED_NOTE}\n\nThe procedure for this skill lives in \`${repoRel(path)}\`, beside its briefs and templates${scripts}. Read that file in full and follow it; every relative file it names is in the same folder.\n`;
}

function commandShim(spec: AgentSpec, profile: AgentProfile): string {
  const profilePath = spec.agentProfile.startsWith("assets/") ? `src/agent-sdk/${spec.agentProfile}` : spec.agentProfile;
  const [contractPath, anchor] = RUN_CONTRACT.split("#") as [string, string];
  const here = `.claude/skills/${spec.name}`;
  const link = (target: string) => relative(fromRepoRoot(here), fromRepoRoot(target));
  const roster = spec.orchestrator
    ? `\n   Orchestrator: this session dispatches; it is never a subagent. Dispatch with the \`Agent\` tool (\`subagent_type\` = a \`.claude/agents/\` agent, \`name\` = the work item, \`run_in_background: false\`); independent rows go out as several calls in ONE message so they run in parallel, each with a disjoint write set. Roster: ${spec.handoffs.join(", ")}.`
    : "";
  return `${frontmatter({ name: spec.name, description: yamlString(profile.description), "argument-hint": '"[request]"', agent_profile: profilePath })}${GENERATED_NOTE}

Command route: runs in this session, not the SDK orchestrator (\`pnpm agents --agent ${spec.name}\` is the headless route).

1. Know what is current: \`python3 src/agent-sdk/assets/tools/repo/state/state.py --intent <intent>\`; run only what it lists. Ask the operator before any metered step.
2. Run profile [\`${profilePath}\`](${link(profilePath)}) per the [run contract](${link(contractPath)}#${anchor}).${roster}

Request: $ARGUMENTS
`;
}

async function subagentShim(spec: AgentSpec, profile: AgentProfile, skills: Map<string, string>, toolCatalog: ToolCatalog): Promise<string> {
  const tools = [...new Set(["Read", "Glob", "Grep", ...spec.tools.flatMap(({ name }) => toolCatalog.groups.get(name)?.toolNames ?? [])])].filter((tool) => NATIVE_TOOLS.has(tool));
  return `${frontmatter({ name: spec.name, description: yamlString(profile.description), tools: tools.join(", ") })}${GENERATED_NOTE}

You are the ${spec.name} subagent, generated from \`src/${"agent-sdk"}/${spec.agentProfile}\`. Stay inside this profile and do not substitute a neighboring role. Change only the files your dispatch assigns you: sibling dispatches may be editing other files right now. You cannot dispatch anyone; report back through your final message. The run contract is \`${RUN_CONTRACT}\`.

Persona: ${profile.persona}

## Goal

${profile.goal}

## Success criteria

${numbered(profile.success_criteria)}

## Skills

${profile.skills.length ? bullets(skillLines(profile, skills)) : "None."}

## Tools

${bullets(await guideLines(profile, toolCatalog))}

${scriptLines(profile, toolCatalog).length ? `## Script tools, as session commands

In the SDK run these are the \`${scriptToolName("<name>")}\` tools; in a session run the command from the repository root through Bash.

${bullets(scriptLines(profile, toolCatalog))}

` : ""}## Input

${bullets(profile.input)}

## Deliver

${profile.output.map((row) => `- \`${row.filename}\`: ${row.key_sections}`).join("\n")}

In a session there is no run ledger: return these as your final message, and write any data files the skill assigns to you under \`data/\`. Escalate only when: ${profile.hitl}
`;
}

/** Every generated pointer, keyed by repo-relative path. Deterministic: same sources, same bytes. */
export async function renderShims(graph: AgentGraph, toolCatalog: ToolCatalog): Promise<Map<string, string>> {
  const skills = await discoverSkills();
  const shims = new Map<string, string>();
  for (const [name, path] of skills) shims.set(`.claude/skills/${name}/SKILL.md`, await skillShim(name, path));
  for (const spec of graph.agents.values()) {
    const profile = await loadAgentProfile(spec);
    if (skills.has(spec.name)) throw new Error(`Agent '${spec.name}' collides with the skill of the same name in ${SKILLS_ROOT}`);
    shims.set(`.claude/skills/${spec.name}/SKILL.md`, commandShim(spec, profile));
    if (!spec.orchestrator) shims.set(`.claude/agents/${spec.name}.md`, await subagentShim(spec, profile, skills, toolCatalog));
  }
  return shims;
}

/** Generated pointers on disk that no source renders: a stale one left by a removed or re-kinded agent or skill. */
export async function extraShims(shims: Map<string, string>): Promise<string[]> {
  const extra: string[] = [];
  const agentsDir = fromRepoRoot(".claude/agents");
  for (const entry of await readdir(agentsDir, { withFileTypes: true }).catch(() => [])) {
    const path = `.claude/agents/${entry.name}`;
    if (!shims.has(path)) extra.push(path);
  }
  const skillsDir = fromRepoRoot(".claude/skills");
  for (const entry of await readdir(skillsDir, { withFileTypes: true }).catch(() => [])) {
    const path = `.claude/skills/${entry.name}/SKILL.md`;
    if (!entry.isDirectory() || !shims.has(path)) extra.push(`.claude/skills/${entry.name}`);
  }
  return extra;
}

export async function writeShims(shims: Map<string, string>): Promise<string[]> {
  const removed = await extraShims(shims);
  for (const path of removed) await rm(fromRepoRoot(path), { recursive: true, force: true });
  for (const [path, content] of shims) {
    await mkdir(dirname(fromRepoRoot(path)), { recursive: true });
    await writeFile(fromRepoRoot(path), content);
  }
  return removed;
}

/** Generated pointers that are missing, differ from what the sources render, or have no source. */
export async function staleShims(shims: Map<string, string>): Promise<string[]> {
  const stale: string[] = [];
  for (const [path, content] of shims) {
    if ((await readFile(fromRepoRoot(path), "utf8").catch(() => undefined)) !== content) stale.push(path);
  }
  return [...stale, ...(await extraShims(shims)).map((path) => `${path} (no source)`)];
}

/**
 * The structural contract of the agent folder, enforced rather than advisory: one agent, one profile
 * (`assets/agents/<name>.yml`), nothing else in `assets/agents/`, and every skill granted by at least
 * one profile.
 */
export async function validateStructure(graph: AgentGraph, skills: Map<string, string>): Promise<void> {
  const entries = await readdir(fromSdkRoot("assets/agents"), { withFileTypes: true });
  const stray = entries.filter((entry) => !entry.isFile() || !entry.name.endsWith(".yml")).map((entry) => entry.name);
  if (stray.length) throw new Error(`assets/agents holds only <agent>.yml profiles; found ${stray.join(", ")}`);
  const orphans = entries.map((entry) => entry.name.slice(0, -4)).filter((name) => !graph.agents.has(name));
  if (orphans.length) throw new Error(`Agent profiles without a graph agent: ${orphans.join(", ")}`);
  for (const spec of graph.agents.values()) {
    if (spec.agentProfile !== `assets/agents/${spec.name}.yml`) throw new Error(`${spec.name}: agentProfile must be assets/agents/${spec.name}.yml (got ${spec.agentProfile})`);
  }
  const orphanSkills = ungrantedSkills(skills, graph.agents.values());
  if (orphanSkills.length) throw new Error(`Skills no agent profile grants: ${orphanSkills.join(", ")}; add {name, disclosure} to a profile's skills or delete the skill`);
}
